blank_issues_enabled: true
contact_links:
  - name: â“ Question
    url: https://discord.com/channels/1060530809309761586/1118159566929154202
    about: Ask a question about Patron
  - name: ğŸ“–  Patron Documentation
    url: https://patron.works/getting-started
    about: The Patron documentation may answer your questions!
  - name: ğŸ’¬  Patron Community Support (Discord)
    url: https://discord.com/channels/1060530809309761586/1118159566929154202
    about: Please ask and answer questions here.
